### ISSUE TITLE
Add ARB:Arbiter

### ISSUE THREAD

**Issue by HarmonyUniverse** [BossSwap/bossswap-default-token-list#1]
**Please provide the following information for your token.**

Token Address\*: 0x044246137670a03ca790d7ed20af0c552c88117c
Token Name (from contract)\*: Arbiter
Token Decimals (from contract)\*: 18
Token Symbol (from contract)\*: ARB
Pair Address of Token ( i.e BOSS/ONE 0x50AB1F2687dF0fD6c66E305f1116cF2A4545313a ): 0xa4dadd1ee348ed44e39e38a14fd7eb9786f72dbe

Link to the official homepage of token: harmonyuniverse.one
Link to CoinMarketCap or CoinGecko page of token: 
Paste in Token Image PNG format ( 96x96 )\*:
![photo_2021-07-26_05-06-47 (1)](https://user-images.githubusercontent.com/92765350/137824627-b6f62135-c740-4dc0-9365-8f3b7b7d007f.png)

**Comment by bigbosssin** [comment]
merged: https://github.com/BossSwap/bossswap-default-token-list/commit/2f097b65c94a3279cec7d54293afb6bcb90a8320
