### ISSUE TITLE
Tranq : Tranquil

### ISSUE THREAD

**Issue by SquidFinder** [BossSwap/bossswap-default-token-list#10]
**Please provide the following information for your token.**

Token Address\*:  0xcf1709ad76a79d5a60210f23e81ce2460542a836
Token Name (from contract)\*:   Tranquil
Token Decimals (from contract)\*: 18
Token Symbol (from contract)\*: TRANQ
Pair Address of Token : 0xa366af6c3f8dec8d0a5921166fbf077580da2776

Link to the official homepage of token: https://www.tranquil.finance/#
Link to CoinMarketCap or CoinGecko page of token:  https://www.coingecko.com/en/coins/tranquil-finance
Paste in Token Image PNG format ( 96x96 )\*:  
![image](https://user-images.githubusercontent.com/83293271/140539821-ea739d67-d32e-41c7-816b-c4217f8e39e5.png)

**Comment by bigbosssin** [comment]
merged: https://github.com/BossSwap/bossswap-default-token-list/commit/ac22308f63f970a4f4827b2bf40813c2d4bed053
