### ISSUE TITLE
Add {Mini}: {Minion}

### ISSUE THREAD

**Issue by SquidFinder** [BossSwap/bossswap-default-token-list#11]
**Please provide the following information for your token.**

Token Address\*:  0x7e503b282fcbe3f2edc03642dccc425d238c334f
Token Name (from contract)\*:  Minion
Token Decimals (from contract)\*:  18
Token Symbol (from contract)\*:  MINI
Pair Address of Token :  
MINI/BOSS = 0x0a8e1a4986453b9cbe0577e2800906813744c037
MINI/ONE =  0xe4b9ddbceca42b91a56187a8274a342957afc523

Link to the official homepage of token:
Link to CoinMarketCap or CoinGecko page of token: 
Paste in Token Image PNG format ( 96x96 )\*:   
![image](https://user-images.githubusercontent.com/83293271/140666847-2d0c2e4b-0371-4447-96c9-fe84b6421cdb.png)

**Comment by SquidFinder** [comment]
Submitting pull specifically to make token searchable without the contract address. Also hoping to get the logo added to the info/charts page.

**Comment by bigbosssin** [comment]
merged https://github.com/BossSwap/bossswap-default-token-list/commit/89b10d28506b93fc9a356bf51e6267f5c26bb4d8
