### ISSUE TITLE
Add {RVRS}: {REVERSE}

### ISSUE THREAD

**Issue by SquidFinder** [BossSwap/bossswap-default-token-list#12]
**Please provide the following information for your token.**

Token Address\*:  0xED0B4b0F0E2c17646682fc98ACe09feB99aF3adE
Token Name (from contract)\*:  Reverse Token
Token Decimals (from contract)\*: 18
Token Symbol (from contract)\*: RVRS
Pair Address of Token :  Boss/RVRS LP 0x479A94865998C758DD76DdC8Eb6B3B3e0c71ea9E

Link to the official homepage of token: Live11/13/2021
Link to CoinMarketCap or CoinGecko page of token: https://dexscreener.com/harmony/0xCDe0A00302CF22B3Ac367201FBD114cEFA1729b4
Paste in Token Image PNG format ( 96x96 )\*:
![image](https://user-images.githubusercontent.com/83293271/141306814-a5fdefd5-9a3c-4742-8c54-dace9706c101.png)

**Comment by bigbosssin** [comment]
merged https://github.com/BossSwap/bossswap-default-token-list/commit/89b10d28506b93fc9a356bf51e6267f5c26bb4d8
