### ISSUE TITLE
Add {MINI}: {MINION}

### ISSUE THREAD

**Issue by SquidFinder** [BossSwap/bossswap-default-token-list#13]
This request is to strictly update the image for the Minion token, the new image has the grey background removed which is clearly visible on the boss swap token menu.  

Token Address\*: 0x7e503b282fcbe3f2edc03642dccc425d238c334f
Token Name (from contract)\*: Minion
Token Decimals (from contract)\*:  18
Token Symbol (from contract)\*:  Mini 
Pair Address of Token :  0xe4b9ddbceca42b91a56187a8274a342957afc523

Link to the official homepage of token:
Link to CoinMarketCap or CoinGecko page of token: 
Paste in Token Image PNG format ( 96x96 )\*:
![image](https://user-images.githubusercontent.com/83293271/142714601-d35a5535-5818-477d-955d-36d9dfbf18cb.png)

**Comment by bigbosssin** [comment]
Merged done
