### ISSUE TITLE
Add {CGS}: {Cougar Token}

### ISSUE THREAD

**Issue by cougarswap** [BossSwap/bossswap-default-token-list#14]
**Please provide the following information for your token.**

Token Address\*: 0x6cc35220349C444c39b8e26b359757739aAEc952
Token Name (from contract)\*: Cougar Token
Token Decimals (from contract)\*: 18
Token Symbol (from contract)\*: CGS
Pair Address of Token : CGS/WONE 0xd1c16602e12fcfb8e1a5716afacda9fed33fbf34

Link to the official homepage of token: https://harmonyapp.cougarswap.io/
Link to CoinMarketCap : https://coinmarketcap.com/currencies/cougar/
Link to CoinGecko: https://www.coingecko.com/en/coins/cougar-token
Paste in Token Image PNG format ( 96x96 )\*: https://harmonyapp.cougarswap.io/logo.png

**Comment by bigbosssin** [comment]
merged: https://github.com/BossSwap/bossswap-default-token-list/commit/b4cfc1113efb19dd1f517beaaa5d1e6babbdbfba
