### ISSUE TITLE
Add {COINKX}: {CryptoPigs Token} 

### ISSUE THREAD

**Issue by SquidFinder** [BossSwap/bossswap-default-token-list#15]
**Please provide the following information for your token.**

Token Address\*: 0x7ca9c1d0bb11f1b7c31ee5538d7a75aaf2d8e2fc
Token Name (from contract)\*: CryptoPigs Token
Token Decimals (from contract)\*: COINKX
Token Symbol (from contract)\*: 18
Pair Address of Token (BOSS/COINKX): 0x3036f94ccdc0e03eee477fe7695220b0a7d96254

Link to the official homepage of token: https://cryptopigs.one/#/
Link to CoinMarketCap or CoinGecko page of token:
Paste in Token Image PNG format ( 96x96 )\*:
![image](https://user-images.githubusercontent.com/83293271/144681796-eddf6314-e53b-4c0f-8770-2c5979fb2b41.png)

**Comment by bigbosssin** [comment]
merged https://github.com/BossSwap/bossswap-default-token-list/commit/2c072d0fa07c8c8888df64a442d3213c1ac64d7e
