### ISSUE TITLE
Add {xB Piggy}: {Baby Piggy}

### ISSUE THREAD

**Issue by SquidFinder** [BossSwap/bossswap-default-token-list#16]
**Please provide the following information for your token.**

Token Address\*:  0x2b24bb17c9bb25668ea01caabd43bf10eaa332eb
Token Name (from contract)\*: Baby Piggy
Token Decimals (from contract)\*:  18
Token Symbol (from contract)\*:  xB Piggy
Pair Address of Token (Coinkx/xB Piggy):  0x1c5ff876c3b005d84b7eaa058c3805606ac6dc59

Link to the official homepage of token:
Link to CoinMarketCap or CoinGecko page of token:  
Paste in Token Image PNG format ( 96x96 )\*: 
![image](https://user-images.githubusercontent.com/83293271/146284026-4087366e-fe4e-4c0b-9dd2-ee0186cdef34.png)

**Comment by SquidFinder** [comment]
On behalf of Baby Dao. Anon Dev, forked and migrated.

**Comment by bigbosssin** [comment]
merged 6b5857d996b8c4fbcd2e885ccae9ae9dd2f49933
