### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by harmonape** [BossSwap/bossswap-default-token-list#17]
**Please provide the following information for your token.**

Token Address\*: 0xd3a50c0dce15c12fe64941ffd2b864e887c9b9e1
Token Name (from contract)\*: Harmonape
Token Decimals (from contract)\*: 9
Token Symbol (from contract)\*: $APE
Pair Address of Token ( i.e BOSS/ONE 0x50AB1F2687dF0fD6c66E305f1116cF2A4545313a ): 

Link to the official homepage of token: https://www.harmonape.com/
Link to CoinMarketCap or CoinGecko page of token: 
Paste in Token Image PNG format ( 96x96 )\*: https://drive.google.com/drive/u/0/mobile/folders/1--RMIavM3Z5j2S6T47NfXMSV09fhU2Gv/1VeFboQ-qxftRn_p4hVauseBeilGacvNj?sort=13&direction=a

**Comment by bigbosssin** [comment]
merged 908605e9c259c37e18e28c2f74e86e1631da859d

**Comment by bigbosssin** [comment]
Currently there isnt BOSS/APE pair address
>Pair Address of Token ( i.e BOSS/ONE 0x50AB1F2687dF0fD6c66E305f1116cF2A4545313a ):
