### ISSUE TITLE
Add MCONE: McOne Coin

### ISSUE THREAD

**Issue by mconecrypto** [BossSwap/bossswap-default-token-list#6]
**Please provide the following information for your token.**

Token Address\*: 0x7531905c4c80b602cff46badc1671fbad496f043
Token Name (from contract)\*: McONE Coin
Token Decimals (from contract)\*: 9
Token Symbol (from contract)\*: MCONE
Pair Address of Token ( i.e BOSS/ONE 0x50AB1F2687dF0fD6c66E305f1116cF2A4545313a ):  0x3481580ab2a0d9c83368bca9d391324d4e8af2db

Link to the official homepage of token: mcone.co
Link to CoinMarketCap or CoinGecko page of token:  coming soon
Paste in Token Image PNG format ( 96x96 )\*
![mcone](https://user-images.githubusercontent.com/85047348/139520072-a2eeed81-7e30-468c-a64b-1eddc4daf7da.png)
:

**Comment by bigbosssin** [comment]
merged: https://github.com/BossSwap/bossswap-default-token-list/commit/9a0ef410e92529d1139495fd6fc8c673c874139f
