### ISSUE TITLE
Add SONIC: Sonic

### ISSUE THREAD

**Issue by SonicSwapDev** [BossSwap/bossswap-default-token-list#7]
**Please provide the following information for your token.**

Token Address\*: 0x1e05C8B69e4128949FcEf16811a819eF2f55D33E
Token Name (from contract)\*: Sonic
Token Decimals (from contract)\*: 18
Token Symbol (from contract)\*: SONIC
Pair Address of Token\*: BOSS/SONIC 0x52b98006ec97837cc3e3c8508463df96715abb11
Link to the official homepage of token: https://sonicswap.io/
Link to CoinMarketCap or CoinGecko page of token:  https://coinmarketcap.com/currencies/sonic-swap/
Paste in Token Image PNG format ( 96x96 )\*:
![SonicSwapNEWLOGO](https://user-images.githubusercontent.com/85848950/139573398-d1514dba-e4d4-45e4-b31b-af4d6aa2d5e1.png)

**Comment by bigbosssin** [comment]
merged: https://github.com/BossSwap/bossswap-default-token-list/commit/9a0ef410e92529d1139495fd6fc8c673c874139f
