### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by Guldpungen** [BossSwap/bossswap-default-token-list#8]
**Please provide the following information for your token.**

Token Address\*: 0x40d2f81bd135b5282cb2aa18f19cf7098079d012
Token Name (from contract)\*: IKURA
Token Decimals (from contract)\*: 9
Token Symbol (from contract)\*: IKURA
Pair Address of Token ( i.e BOSS/ONE 0x50AB1F2687dF0fD6c66E305f1116cF2A4545313a ): 0x8befddff3a846693efbe496c06b2520414aadabc

Link to the official homepage of token: https://app.ikura.one/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/coins/ikura-token
Paste in Token Image PNG format ( 96x96 )\*: i will send this on telegram as soon as I have it.

**Comment by bigbosssin** [comment]
merged: https://github.com/BossSwap/bossswap-default-token-list/commit/ac22308f63f970a4f4827b2bf40813c2d4bed053
