### ISSUE TITLE
Add {FOOL}: {Fool}

### ISSUE THREAD

**Issue by defigraal** [BossSwap/bossswap-default-token-list#9]
**Please provide the following information for your token.**

Token Address\*: 0x584705c40e7df1fcfc06cb0ad5223e0f5bc8e6e2
Token Name (from contract)\*: Fool
Token Decimals (from contract)\*: 18
Token Symbol (from contract)\*: FOOL
Pair Address of Token ( i.e BOSS/ONE 0x50AB1F2687dF0fD6c66E305f1116cF2A4545313a ): 0x67367e49ecee9477c2db11d81999fba2551b37cf

Link to the official homepage of token: (short term solution) https://lootswap.finance/guilds/fool
Link to CoinMarketCap or CoinGecko page of token: na
Paste in Token Image PNG format ( 96x96 )\*:
![fool-token-img](https://user-images.githubusercontent.com/87538298/140213692-724f4415-47ea-47f5-9bba-3bf02440f449.png)

**Comment by bigbosssin** [comment]
merged: https://github.com/BossSwap/bossswap-default-token-list/commit/ac22308f63f970a4f4827b2bf40813c2d4bed053
